[package]
name = "tips-datastore"
version.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
sqlx.workspace = true
uuid.workspace = true
tokio.workspace = true
anyhow.workspace = true
async-trait.workspace = true
alloy-rpc-types-mev.workspace = true
alloy-primitives.workspace = true
tracing.workspace = true
tips-common.workspace = true

[dev-dependencies]
testcontainers.workspace = true
testcontainers-modules.workspace = true
