[package]
name = "tips-datastore"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx.workspace = true
uuid.workspace = true
tokio.workspace = true
anyhow.workspace = true
async-trait.workspace = true
alloy-rpc-types-mev.workspace = true
alloy-primitives.workspace = true
alloy-consensus.workspace = true
op-alloy-consensus.workspace = true
eyre.workspace = true
tracing.workspace = true

[dev-dependencies]
testcontainers.workspace = true
testcontainers-modules.workspace = true
