[package]
name = "tips-common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
alloy-rpc-types-mev.workspace = true
alloy-primitives.workspace = true
sqlx.workspace = true
