services:
  simulator-cl:
    image: base-node-reth
    container_name: tips-simulator-cl
    ports:
      - "18545:8545" # RPC
      - "19222:9222" # P2P TCP
      - "19222:9222/udp" # P2P UDP
      - "17300:7300" # metrics
      - "16060:6060" # pprof
    # As written, op-node-entrypoint must write its own JWT secret to the file system.
    command:
      - bash
      - -c
      - |
          echo "Writing JWT secret to $${OP_NODE_L2_ENGINE_AUTH}"
          cat /data/jwtsecret > "$${OP_NODE_L2_ENGINE_AUTH}"
          export OP_NODE_P2P_BOOTNODES=$(grep 'enr=' /artifacts/logs/op-node.log | sed -n 's/.*enr=\([^ ]*\).*/\1/p')
          eval "OP_NODE_L2_ENGINE_HTTP=\$${OP_NODE_L2_ENGINE_RPC/ws/http}"
          until [ "$(curl -s -w '%{http_code}' -o /dev/null "$${OP_NODE_L2_ENGINE_HTTP}")" -eq 401 ]; do
            echo "waiting for execution client to be ready"
            sleep 5
          done
          exec ./op-node
    volumes:
      - ~/.playground/devnet:/artifacts
      - ~/.playground/devnet/jwtsecret:/data/jwtsecret
      - ~/.playground/devnet/rollup.json:/data/rollup.json
    env_file:
      - ${NETWORK_ENV:-.env.playground}


