services:
  simulator-cl:
    image: base-node-reth
    container_name: tips-simulator-cl
    ports:
      - "18545:8545" # RPC
      - "19222:9222" # P2P TCP
      - "19222:9222/udp" # P2P UDP
      - "17300:7300" # metrics
      - "16060:6060" # pprof
    # As written, op-node-entrypoint must write its own JWT secret to the file system.
    command:
      - bash
      - -c
      - |
          OP_NODE_L2_ENGINE_AUTH_RAW=$(cat /data/jwtsecret)
          OP_NODE_P2P_BOOTNODES=$(grep 'enr=' /artifacts/logs/op-node.log | sed -n 's/.*enr=\([^ ]*\).*/\1/p')
          export OP_NODE_L2_ENGINE_AUTH_RAW OP_NODE_P2P_BOOTNODES
          exec ./op-node-entrypoint
    volumes:
      - ~/.playground/devnet/:/artifacts
      - ~/.playground/devnet/jwtsecret:/data/jwtsecret
      - ~/.playground/devnet/rollup.json:/data/rollup.json
    env_file:
      - ${NETWORK_ENV:-.env.playground}


