name: UI
permissions:
  contents: read

on:
  push:
    branches: [ master ]
    paths: ['ui/**']
  pull_request:
    paths: ['ui/**']

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: ui/yarn.lock
      - run: cp .env.example ui/.env
      - run: cd ui && yarn install
      - run: cd ui && yarn lint

  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: ui/yarn.lock
      - run: cp .env.example ui/.env
      - run: cd ui && yarn install
      - run: cd ui && npx tsc --noEmit

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: ui/yarn.lock
      - run: cp .env.example ui/.env
      - run: cd ui && yarn install
      - run: cd ui && yarn build